import { motion } from "framer-motion";
import {
  MapPin,
  Calendar,
  Sparkles,
  Clock3,
  Plane,
  Globe,
} from "lucide-react";

import DestinationImage from "./DestinationImage";

function StatCard({ icon, title, value }) {
  return (
    <motion.div
      whileHover={{ y: -4 }}
      transition={{ duration: 0.25 }}
      className="rounded-2xl border border-white/60 bg-white/70 p-5 backdrop-blur-xl shadow-md"
    >
      <div className="mb-3 flex h-12 w-12 items-center justify-center rounded-xl bg-orange-100 text-orange-600">
        {icon}
      </div>

      <p className="text-sm text-slate-500">
        {title}
      </p>

      <h3 className="mt-1 font-bold text-slate-800">
        {value}
      </h3>
    </motion.div>
  );
}

function ItineraryCard({ data }) {
  if (!data) return null;

  return (
    <motion.div
      initial={{ opacity: 0, y: 35 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6 }}
      className="mt-14 overflow-hidden rounded-[36px] bg-white shadow-[0_30px_70px_rgba(15,23,42,.12)]"
    >
      {/* ================= HERO ================= */}

      <div className="relative h-[420px] overflow-hidden">

        <DestinationImage
          destination={data.destination}
          image={data.image}
        />

        <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/35 to-transparent" />

        {/* Destination Badge */}

        <motion.div
          initial={{ opacity: 0, y: -15 }}
          animate={{ opacity: 1, y: 0 }}
          className="absolute left-7 top-7 flex items-center gap-2 rounded-full bg-white/20 px-5 py-2 text-sm font-medium text-white backdrop-blur-xl"
        >
          <MapPin size={16} />
          {data.destination}
        </motion.div>

        {/* Hero Text */}

        <div className="absolute bottom-10 left-10">

          <motion.h1
            initial={{ opacity: 0, y: 25 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: .15 }}
            className="text-5xl font-black tracking-tight text-white drop-shadow-xl md:text-6xl"
          >
            {data.destination}
          </motion.h1>

          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: .3 }}
            className="mt-4 max-w-xl text-lg leading-8 text-white/90"
          >
            {data.summary}
          </motion.p>

        </div>

      </div>

      {/* ================= BODY ================= */}

      <div className="relative bg-gradient-to-b from-stone-50 via-white to-orange-50/30 px-8 pb-10">

        {/* Floating Dashboard */}

        <motion.div
          initial={{ opacity: 0, y: 25 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: .35 }}
          className="-mt-16 relative z-20 mb-12"
        >
          <div className="grid gap-5 rounded-[30px] border border-white/50 bg-white/75 p-6 shadow-2xl backdrop-blur-xl md:grid-cols-4">

            <StatCard
              icon={<Calendar size={22} />}
              title="Duration"
              value={data.duration}
            />

            <StatCard
              icon={<Globe size={22} />}
              title="Destination"
              value={data.destination}
            />

            <StatCard
              icon={<Sparkles size={22} />}
              title="Generated By"
              value="Travora AI"
            />

            <StatCard
              icon={<Plane size={22} />}
              title="Experience"
              value="Premium"
            />

          </div>
        </motion.div>

        {/* Overview */}

        <div className="mb-10 rounded-[28px] border border-orange-100 bg-white/80 p-8 shadow-lg backdrop-blur-xl">

          <div className="mb-4 flex items-center gap-3">

            <div className="rounded-xl bg-orange-100 p-3 text-orange-600">
              <Sparkles size={20} />
            </div>

            <h2 className="text-2xl font-bold text-slate-800">
              Trip Overview
            </h2>

          </div>

          <p className="text-lg leading-9 text-slate-600">
            {data.summary}
          </p>

        </div>

        {/* ================= TIMELINE STARTS HERE ================= */}

        <div className="space-y-8">
            {data.itinerary?.map((day, dayIndex) => (
  <motion.div
    key={day.day}
    initial={{ opacity: 0, y: 40 }}
    whileInView={{ opacity: 1, y: 0 }}
    viewport={{ once: true }}
    transition={{
      delay: dayIndex * 0.08,
      duration: 0.45,
    }}
    className="
      group
      relative
      overflow-hidden
      rounded-[30px]
      border
      border-stone-200
      bg-white
      shadow-lg
      transition-all
      duration-300
      hover:-translate-y-1
      hover:shadow-2xl
      before:absolute
      before:left-0
      before:top-0
      before:h-full
      before:w-2
      before:bg-gradient-to-b
      before:from-orange-500
      before:to-amber-400
    "
  >
    <div className="p-8">

      {/* Day Header */}

      <div className="mb-8 flex items-center gap-5">

        <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-orange-500 to-orange-600 text-white shadow-xl">
          <Clock3 size={28} />
        </div>

        <div>

          <p className="text-sm font-medium uppercase tracking-[4px] text-orange-500">
            Travel Schedule
          </p>

          <h2 className="mt-1 text-3xl font-black text-slate-800">
            Day {day.day}
          </h2>

        </div>

      </div>

      {/* Activities */}

      <div className="space-y-5">

        {day.activities?.map((activity, i) => (

          <motion.div
            key={i}
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{
              delay: i * 0.06,
            }}
            whileHover={{
              x: 8,
            }}
            className="
              flex
              items-start
              gap-5
              rounded-2xl
              border
              border-slate-100
              bg-slate-50
              p-5
              transition-all
              duration-300
              hover:bg-white
              hover:shadow-md
            "
          >

            <div className="mt-1 flex h-12 w-12 items-center justify-center rounded-full bg-orange-100">

              <MapPin
                size={20}
                className="text-orange-600"
              />

            </div>

            <div className="flex-1">

              <p className="text-lg leading-8 text-slate-700">
                {activity}
              </p>

            </div>

          </motion.div>

        ))}

      </div>

    </div>

  </motion.div>

))}
        </div>

        {/* ================= TRAVEL TIP ================= */}

        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="mt-14 overflow-hidden rounded-[30px] bg-gradient-to-r from-orange-500 via-orange-600 to-amber-500 p-8 text-white shadow-[0_20px_50px_rgba(249,115,22,.35)]"
        >
          <div className="flex items-center gap-4">

            <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-white/20 backdrop-blur-xl">
              <Plane size={28} />
            </div>

            <div>

              <h2 className="text-2xl font-bold">
                Pro Travel Tip
              </h2>

              <p className="text-orange-100">
                Make the most of your adventure
              </p>

            </div>

          </div>

          <div className="mt-6 grid gap-4 md:grid-cols-2">

            <div className="rounded-2xl bg-white/10 p-5 backdrop-blur-lg">
              📄 Carry digital copies of important travel documents and keep
              them backed up online.
            </div>

            <div className="rounded-2xl bg-white/10 p-5 backdrop-blur-lg">
              💳 Keep a mix of cash and international payment methods for
              convenience.
            </div>

            <div className="rounded-2xl bg-white/10 p-5 backdrop-blur-lg">
              📱 Download offline maps before travelling to avoid connectivity
              issues.
            </div>

            <div className="rounded-2xl bg-white/10 p-5 backdrop-blur-lg">
              ⭐ Leave some free time in your schedule to explore hidden local
              attractions.
            </div>

          </div>
        </motion.div>

        {/* Footer */}

        <div className="mt-12 text-center">

          <div className="inline-flex items-center gap-3 rounded-full border border-orange-200 bg-white px-6 py-3 shadow-md">

            <Sparkles
              size={18}
              className="text-orange-500"
            />

            <span className="font-medium text-slate-700">
              Powered by Travora AI
            </span>

          </div>

        </div>

      </div>

    </motion.div>
  );
}

export default ItineraryCard;